name: CustomWeapons
version: 1.0.2
author: _FlowZz_
main: it.flowzz.customweapons.CustomWeaponsPlugin
commands:
  cweapons:
    description: Base command to give custom weapons.
    aliases: [customweapon,customweapons,cweapon]